import { GoogleGenerativeAI } from '@google/generative-ai';
import { SoapNote } from '../types';

const API_KEY = import.meta.env.VITE_GEMINI_API_KEY || '';

// --- Helper: Dynamic Model Discovery ---
async function getActiveModelName(): Promise<string> {
    try {
        // Try to fetch available models to find the smartest/fastest one
        const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${API_KEY}`);
        const data = await res.json();
        
        if (data.models) {
            const names = data.models.map((m: any) => m.name.replace('models/', ''));
            // Prioritize 1.5 Flash or Pro for speed + context window
            const bestModel = names.find((n: string) => n.includes('gemini-1.5-pro')) ||
                              names.find((n: string) => n.includes('gemini-1.5-flash')) ||
                              'gemini-1.5-flash';
            return bestModel;
        }
    } catch (e) {
        console.error("Model discovery failed, falling back to 1.5-flash", e);
    }
    return 'gemini-1.5-flash';
}

const genAI = new GoogleGenerativeAI(API_KEY);

export const generateSoapNote = async (transcript: string): Promise<SoapNote> => {
    // Fallback simulation if no key or empty text
    if (!API_KEY || !transcript.trim()) return simulateSoapNote();

    try {
        const modelName = await getActiveModelName();
        
        const model = genAI.getGenerativeModel({ 
            model: modelName,
            // We ask for JSON specifically to avoid parsing errors
            generationConfig: { responseMimeType: "application/json" }
        });

        // --- SPECIALIZED PROMPT FOR MOBILE DICTATION ---
        // This prompts helps Gemini understand that the text might be "bad English" 
        // that is actually Bisaya/Cebuano phonetically transcribed.
        const prompt = `
        You are an expert Pediatric Scribe for Dr. Atamosa in Cebu, Philippines.
        
        TASK: Convert the following raw consultation transcript into a professional medical SOAP Note JSON.

        CRITICAL CONTEXT:
        1. The transcript was generated by an English speech-to-text engine.
        2. The doctor and patient likely spoke a mix of **English and Bisaya (Cebuano)**.
        3. **PHONETIC CORRECTION:** If you see English words that make no sense contextually, interpret them as phonetic Bisaya. 
           (Example: "Socket sa ulu" should be interpreted as "Sakit sa ulo" -> "Headache").
        4. Translate everything into standard Clinical English.

        RAW TRANSCRIPT:
        "${transcript}"

        OUTPUT SCHEMA (JSON Only):
        {
          "subjective": "History of present illness, chief complaints (translated to English)",
          "objective": "Physical findings, vitals mentioned, observations",
          "assessment": "Diagnosis or clinical impression",
          "plan": "Medications, treatment instructions, follow-up"
        }
        `;

        const result = await model.generateContent(prompt);
        const text = result.response.text();
        
        // Parse the JSON safely
        return JSON.parse(text);

    } catch (error) {
        console.error("SOAP Generation Error:", error);
        return simulateSoapNote();
    }
};

// --- Fallback Data ---
const simulateSoapNote = (): SoapNote => ({
    subjective: "Unable to process transcript via AI. Please check internet or API Key.",
    objective: "No exam data extracted.",
    assessment: "Consultation Record (Manual Entry Required)",
    plan: "Review transcript and edit manually."
});